pipeline yml + terraform file

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -76,15 +76,44 @@ stages:
             pool:
               vmImage: 'ubuntu-latest'                       
             steps:
-             - script: echo My first job
+             - script: |
+                # Exit when any commands returns a failure status
+                 set -e 
+
+                # create and write terraform.tvars  
+                 echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
+              
+                 # create and write backend.tfvars
+                 echo 'resource_group_name = "tf-storage-rg"' | tee backend.tfvars
+                 echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend.tfvars
+                 echo 'container_name = "tfstate"' | tee -a backend.tfvars
+                 echo 'key = "dev.terraform.tfstate"' | tee -a backend.tfvars
+
+                 # terraform init
+                   terraform init -input=false -backend="backend.tfvars"
+                
+                 # terraform apply with auto approve
+                   terraform apply -input=false -auto-approve
+
+                 # terraform retrieve output  and set pipeline variable
+                   WebAppNameDev=$(terraform output appservice_name_dev) 
+                   echo "##vso[task.setvariable variable=WebAppNameDev;isOutput=true]$WebAppNameDev"
+               name: 'RunTerraform'
+               displayName: 'Run Terraform'
+               env:
+                ARM_CLIENT_ID: $(ARM_CLIENT_ID)
+                ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
+                ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
+                ARM_TENANT_ID: $(ARM_TENANT_ID)
 
           - deployment: DeployWeb
             displayName: 'Deployment of Space Game web application'
+            dependsOn: Provisionning
             pool:
               vmImage: 'Ubuntu-18.04'
             environment: 'dev'
             variables:
-              - group : Release
+              WebAppNameDev: $[dependencies.Provisionning.outputs['RunTerraform.WebAppNameDev']]
             strategy:
              runOnce:
                deploy:
@@ -96,7 +125,7 @@ stages:
                      inputs:
                        appType: webAppLinux
                        azureSubscription: 'Space-game-azurerm-connection'
-                       appName: '$(webAppNameDEV)'
+                       appName: '$(WebAppNameDEV)'
                        package: '$(Pipeline.Workspace)/drop/$(buildconfiguration)/*.zip'
       
     
